allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - next
  - '@next/swc-*'
  - '@next/env'
  - react
  - react-dom
  - '@types/node'
  - '@types/react'
  - '@types/react-dom'
  - eslint
overrides:
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
